#### gradient descent (SVM, Logistic Regression) give high accuracy when dataset is large
#### KNN give high accuracy when dataset is small.
#### Decision Tree give high accuracy when dataset is large too.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

%matplotlib inline
sns.set(rc={'figure.figsize': [10, 10]}, font_scale=1.2)

In [2]:
df = pd.read_csv('sentiment.csv',sep='\t',names=['Liked','Tweet'])

In [3]:
df

Liked                                              Tweet
0         1            The Da Vinci Code book is just awesome.
1         1  this was the first clive cussler i've ever rea...
2         1                   i liked the Da Vinci Code a lot.
3         1                   i liked the Da Vinci Code a lot.
4         1  I liked the Da Vinci Code but it ultimatly did...
...     ...                                                ...
6913      0                     Brokeback Mountain was boring.
6914      0       So Brokeback Mountain was really depressing.
6915      0  As I sit here, watching the MTV Movie Awards, ...
6916      0    Ok brokeback mountain is such a horrible movie.
6917      0   Oh, and Brokeback Mountain was a terrible movie.

[6918 rows x 2 columns]

In [4]:
x = df["Tweet"]
y = df["Liked"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=22)

In [5]:
tfidv = TfidfVectorizer(stop_words='english')
tfidv.fit(x_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [6]:
x_train = tfidv.transform(x_train)
x_test = tfidv.transform(x_test)

In [7]:
x_train.shape

(5534, 1619)

In [8]:
pd.DataFrame(x_train.toarray(), columns=tfidv.get_feature_names())

007   10  10pm   12   17  1984  1st  200  2007  286  ...  yes  \
0     0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
1     0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
2     0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
3     0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
4     0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
...   ...  ...   ...  ...  ...   ...  ...  ...   ...  ...  ...  ...   
5529  0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
5530  0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
5531  0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
5532  0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   
5533  0.0  0.0   0.0  0.0  0.0   0.0  0.0  0.0   0.0  0.0  ...  0.0   

      yesterday  yip  young  younger  yuck  yuh  zach  zen   µª  
0           0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
1           0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
2           0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
3           0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
4           0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
...         ...  ...    ...      ...   ...  ...   ...  ...  ...  
5529        0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
5530        0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
5531        0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
5532        0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  
5533        0.0  0.0    0.0      0.0   0.0  0.0   0.0  0.0  0.0  

[5534 rows x 1619 columns]

In [9]:
tfidv.get_feature_names()

['007',
 '10',
 '10pm',
 '12',
 '17',
 '1984',
 '1st',
 '200',
 '2007',
 '286',
 '2nd',
 '31st',
 '33',
 '3333',
 '385',
 '50',
 '517',
 '648',
 '6th',
 '700',
 '7th',
 '8230',
 '9am',
 'aaron',
 'able',
 'abortion',
 'abrams',
 'absolutely',
 'absurd',
 'academy',
 'acceptable',
 'accompaniment',
 'account',
 'achieved',
 'aching',
 'acne',
 'acoustic',
 'acting',
 'action',
 'actor',
 'actors',
 'actually',
 'add',
 'addition',
 'admired',
 'admiring',
 'adorable',
 'adore',
 'adult',
 'afterschool',
 'ago',
 'agree',
 'agreed',
 'ah',
 'aka',
 'al',
 'allegedly',
 'amazing',
 'amazingly',
 'america',
 'amã',
 'anatomy',
 'ang',
 'angel',
 'angels',
 'angle',
 'anime',
 'aniwae',
 'anne',
 'answers',
 'anyways',
 'ap',
 'apart',
 'apologized',
 'apparently',
 'appeal',
 'appeals',
 'aren',
 'arenas',
 'arguments',
 'arse',
 'artemis',
 'article',
 'ashamed',
 'asian',
 'aside',
 'ask',
 'asking',
 'asleep',
 'ass',
 'asshole',
 'association',
 'astonishingly',
 'ate',
 'atrocious',
 

## KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

In [11]:
model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [12]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [13]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [14]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [15]:
accuracy_score(y_test, y_pred)

0.976878612716763

## SVM

In [16]:
from sklearn.svm import SVC

In [17]:
model = SVC(kernel='linear')

In [18]:
model.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
y_test

4339    0
6103    0
5457    0
5021    0
4062    0
       ..
4335    0
5535    0
6828    0
6071    0
6244    0
Name: Liked, Length: 1384, dtype: int64

In [21]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [22]:
confusion_matrix(y_test, y_pred)

array([[593,   5],
       [  2, 784]], dtype=int64)

In [23]:
accuracy_score(y_test, y_pred)

0.994942196531792

## Logistic regression

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [25]:
model.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
y_test

4339    0
6103    0
5457    0
5021    0
4062    0
       ..
4335    0
5535    0
6828    0
6071    0
6244    0
Name: Liked, Length: 1384, dtype: int64

In [28]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [29]:
confusion_matrix(y_test, y_pred)

array([[591,   7],
       [  2, 784]], dtype=int64)

In [30]:
accuracy_score(y_test, y_pred)

0.9934971098265896

## Decision Tree

In [31]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [32]:
model.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [33]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
y_test

4339    0
6103    0
5457    0
5021    0
4062    0
       ..
4335    0
5535    0
6828    0
6071    0
6244    0
Name: Liked, Length: 1384, dtype: int64

In [35]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [36]:
confusion_matrix(y_test, y_pred)

array([[583,  15],
       [  7, 779]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred)

0.9841040462427746